import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { getIsLogin } from "./utils/supabase/server";
import LogoutButton from "./_components/auth/LogoutButton";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const isLogin = await getIsLogin();
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <header>
                    {isLogin ? (
                        <LogoutButton />
                    ) : (
                        <>
                            <Link href={"/signup"}>회원가입</Link>
                            <Link href={"/login"}>로그인</Link>
                        </>
                    )}
                    <Link href={"/"}>홈</Link>
                </header>
                {children}
            </body>
        </html>
    );
}
